[global]
Format=2
Tools.Enabled=true
Tools.ApproachDistance=0.5
Tools.MoveSpeed=0.05
Tools.TurnSpeed=2

[Arm 1]
;No Heads, Mount or merge-name lists are required.
Tools.ScanHeadMerges=true
Tools.ScanStandMerges=true
Tools.ScanParkMerges=true
