[global]
Format=2
;Only needed when you want explicit pairing. Otherwise partners are detected.
Link.ArmPB=Arm PB
Tools.Enabled=true
Tools.ApproachDistance=0.5
Tools.MoveSpeed=0.05
Tools.TurnSpeed=2

[Arm 1]
Tools.ScanHeadMerges=true

[Arm 2]
Tools.ScanHeadMerges=true
