(function () {
  'use strict';
  const C = PanelCore, seed = JSON.parse(document.getElementById('initial-data').textContent), $ = id => document.getElementById(id);
  const assets = new Map(seed.assets.map(asset => [asset.id, {...asset, ...C.assetFromSVG(asset.id, asset.name, asset.svg, asset.category), thumbnail: asset.thumbnail, custom: false}]));
  const serializer = new XMLSerializer(), MIME = 'application/x-autoarm-panel';
  const icons = {add:'<path d="M8 2v12M2 8h12"/>',remove:'<path d="M3 4h10M6 4V2h4v2M5 4l1 10h4l1-10M7 6v6M9 6v6"/>',up:'<path d="m3 10 5-5 5 5"/>',down:'<path d="m3 6 5 5 5-5"/>'};
  const icon = name => `<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]}</svg>`;
  const presets = {original:{lineScope:'rules'},workshop:{text:'#e5edf0',line:'#849da9',lineScope:'rules'},paper:{text:'#263e4b',line:'#496370',lineScope:'rules'},contrast:{text:'#ffffff',line:'#ffffff',lineScope:'rules'}};
  ['new-group'].forEach(id => $(id).innerHTML = icon('add'));
  $('delete-group').innerHTML = icon('remove');
  let state = C.validateTemplate(seed.templates[0], assets), currentGroup = state.groups[0].id, selected = -1, selectedElement = '', activeColour = '';
  let busy = false, zoom = 1, toastTimer, editorKeys = [], paints = null, hoverTargets = [], drag = null, pan = null, dragPayload = null, pointerDrop = null, suppressClick = 0, serial = 0, hoverFrame = 0;
  let editingColour = false, draftMembers = null, lastHoverNode = null, lastHoverEvent = null;
  const uniqueID = prefix => `${prefix}-${Date.now()}-${serial++}`;
  const group = () => state.groups.find(item => item.id === currentGroup) || state.groups[0];
  const entry = () => group().panels[selected];
  const colourGroup = () => state.colourGroups.find(item => item.id === activeColour);
  const filename = asset => asset.id.split('/').at(-1);
  const option = (value, label) => {const node = document.createElement('option'); node.value = value; node.textContent = label; return node;};
  const memberKey = member => JSON.stringify([member.group,member.panel,member.element,member.paint]);
  const payload = () => ({...C.copy(state),assets:[...assets.values()].filter(asset=>asset.custom).map(({id,name,category,svg})=>({id,name,category,svg}))});

  function status(message, error = false, keep = false) {
    clearTimeout(toastTimer); $('status-message').textContent = message; $('status').classList.toggle('error',error); $('status').hidden = false;
    if (!error && !keep) toastTimer = setTimeout(() => $('status').hidden = true, 4200);
  }
  $('close-status').onclick = () => {$('status').hidden = true; clearTimeout(toastTimer);};
  function persist() {try {localStorage.setItem('autoarm-panel-assembler-v1',JSON.stringify(payload()));} catch (_) {status('Save a template to keep these changes after closing.',false);}}
  function dismissOldDownload() {$('download-link').hidden = true;}
  function setPane(value) {document.body.dataset.pane = value; document.querySelectorAll('.pane-tabs button').forEach(button=>button.setAttribute('aria-selected',String(button.dataset.pane===value))); requestAnimationFrame(applyZoom);}
  document.querySelectorAll('.pane-tabs button').forEach(button=>button.onclick=()=>setPane(button.dataset.pane));
  document.addEventListener('pointerdown',()=>suppressClick=0,true);

  function categories() {
    const category = $('category').value;
    $('category').replaceChildren(option('','All panels'),...[...new Set([...assets.values()].map(asset=>asset.category))].map(value=>option(value,value)));
    $('category').value = category; $('asset-count').textContent = `${assets.size} SVGs`;
  }
  function thumbnail(asset) {
    if (asset.thumbnail) return asset.thumbnail;
    return 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(asset.svg);
  }
  function renderLibrary() {
    const term = $('search').value.toLowerCase(), category = $('category').value;
    const found = [...assets.values()].filter(asset=>(!category||asset.category===category)&&`${asset.name} ${asset.id}`.toLowerCase().includes(term));
    $('asset-list').replaceChildren(...found.map(asset=>{
      const button = document.createElement('button'); button.className='asset-row'; button.draggable=false; button.dataset.asset=asset.id; button.setAttribute('aria-label',`Add ${filename(asset)}`);
      const thumb = document.createElement('span'); thumb.className='thumbnail'; const image=document.createElement('img'); image.src=thumbnail(asset); image.alt=''; image.loading='lazy'; image.draggable=false; thumb.append(image);
      const title=document.createElement('strong'); title.textContent=filename(asset);button.title=filename(asset);button.append(title,thumb);
      button.onclick=()=>{if(performance.now()<suppressClick)return;addAsset(asset.id,group()); status(`Added ${filename(asset)} to ${group().name}.`);};
      wirePointerDrag(button,{asset:asset.id});
      button.ondragstart=event=>{dragPayload={asset:asset.id};event.dataTransfer.setData(MIME,JSON.stringify(dragPayload)); event.dataTransfer.setData('text/plain',asset.id); event.dataTransfer.effectAllowed='copy'; button.classList.add('dragging');};
      button.ondragend=()=>{dragPayload=null;button.classList.remove('dragging'); clearDropHighlights();}; return button;
    }));
    if (!found.length) $('asset-list').textContent='No matching files.';
  }
  function cleanMemberships() {
    const owners = new Map(state.groups.flatMap(item=>item.panels.map(panel=>[panel.id,item.id])));
    for (const colour of state.colourGroups) colour.members=colour.members.filter(member=>owners.has(member.panel)).map(member=>({...member,group:owners.get(member.panel)}));
    if(draftMembers)draftMembers=new Map([...draftMembers.values()].filter(member=>owners.has(member.panel)).map(member=>{const updated={...member,group:owners.get(member.panel)};return[memberKey(updated),updated];}));
  }
  function startPoster(item) {
    const inner=item.width-2*item.padding, columns=inner-item.gap>240?2:1, width=(inner-item.gap*(columns-1))/columns;
    let y=item.padding;
    for(let index=0;index<item.panels.length;index+=columns){let rowHeight=0; for(let offset=0;offset<columns&&index+offset<item.panels.length;offset++){const panel=item.panels[index+offset],asset=assets.get(panel.asset); panel.width=width; panel.x=item.padding+offset*(width+item.gap); panel.y=y; rowHeight=Math.max(rowHeight,width*asset.height/asset.width);} y+=rowHeight+item.gap;}
    item.minHeight ||= 900; item.snap ??= true;
  }
  function addAsset(id,item,index=item.panels.length,point=null) {
    const panel={id:uniqueID('panel'),asset:id,theme:{},elements:{}};
    if(item.layout==='poster'){const inner=item.width-2*item.padding;panel.width=item.panels[0]?.width||(inner-item.gap>120?(inner-item.gap)/2:inner);panel.x=Math.max(item.padding,point?.x??item.padding);panel.y=Math.max(item.padding,point?.y??item.padding);if(!point&&item.panels.length){const layout=C.layoutGroup(item,assets),height=panel.width*assets.get(id).height/assets.get(id).width,columns=Math.max(1,Math.floor((layout.width-2*item.padding+item.gap)/(panel.width+item.gap))),rowHeight=Math.max(height,...layout.placements.map(placement=>placement.height));for(let slot=0;slot<10000;slot++){const x=item.padding+(slot%columns)*(panel.width+item.gap),y=item.padding+Math.floor(slot/columns)*(rowHeight+item.gap);if(!layout.placements.some(placement=>x<placement.x+placement.width&&x+panel.width>placement.x&&y<placement.y+placement.height&&y+height>placement.y)){panel.x=x;panel.y=y;break;}}}}
    item.panels.splice(index,0,panel); currentGroup=item.id; selected=index; selectedElement=''; renderGroupControls(); changed();
  }
  function clearDropHighlights(){document.querySelectorAll('.drop-over,.drop-before,.drop-after').forEach(node=>node.classList.remove('drop-over','drop-before','drop-after'));}
  function dropData(event) {try{return JSON.parse(event.dataTransfer.getData(MIME));}catch(_){const id=event.dataTransfer.getData('text/plain');return assets.has(id)?{asset:id}:null;}}
  function receiveDrop(event,item,index=item.panels.length,point=null,suppliedData=null) {
    event.preventDefault(); event.stopPropagation(); clearDropHighlights(); if(busy)return;
    const data=suppliedData||dropData(event); if(!data)return;
    if(data.asset&&assets.has(data.asset)){addAsset(data.asset,item,index,point);return;}
    const owner=state.groups.find(candidate=>candidate.id===data.group), oldIndex=owner?.panels.findIndex(panel=>panel.id===data.panel);
    if(!owner||oldIndex<0)return;
    const panel=owner.panels[oldIndex];
    if(owner===item){const target=Math.max(0,Math.min(item.panels.length-1,index>oldIndex?index-1:index)); item.panels=C.movePanel(item.panels,oldIndex,target); selected=target;}
    else {owner.panels.splice(oldIndex,1); item.panels.splice(index,0,panel); selected=index; if(item.layout==='poster'){panel.width=panel.width||item.width/2; panel.x=Math.max(item.padding,point?.x??item.padding); panel.y=Math.max(item.padding,point?.y??item.padding);}}
    currentGroup=item.id; cleanMemberships(); selectedElement=''; renderGroupControls(); changed();
  }
  function makeDropTarget(node,item,index) {
    const below=event=>Number.isInteger(index)&&event.clientY>=node.getBoundingClientRect().top+node.getBoundingClientRect().height/2;
    node.ondragover=event=>{if(!busy){event.preventDefault();event.stopPropagation();node.classList.add('drop-over');if(Number.isInteger(index)){node.classList.toggle('drop-before',!below(event));node.classList.toggle('drop-after',below(event));}event.dataTransfer.dropEffect=dragPayload?.asset?'copy':'move';}};
    node.ondragleave=()=>node.classList.remove('drop-over','drop-before','drop-after'); node.ondrop=event=>receiveDrop(event,item,Number.isInteger(index)?index+(below(event)?1:0):index);
  }
  function wirePointerDrag(node,data){node.addEventListener('pointerdown',event=>{if(busy||event.button!==0||event.target.closest('input,.icon-button'))return;pointerDrop={node,data,pointer:event.pointerId,startX:event.clientX,startY:event.clientY,active:false,ghost:null,target:null};});}
  function pointerDestination(event){const hit=document.elementFromPoint(event.clientX,event.clientY);if(!hit)return null;const tab=hit.closest('.group-tab');if(tab)return{node:tab,item:state.groups.find(item=>item.id===tab.dataset.groupId)};const row=hit.closest('.order-row');if(row){const index=group().panels.findIndex(panel=>panel.id===row.dataset.panelId),below=event.clientY>=row.getBoundingClientRect().top+row.getBoundingClientRect().height/2;return{node:row,item:group(),index:index+(below?1:0),below};}const list=hit.closest('#panel-order');if(list)return{node:list,item:group()};const frame=hit.closest('#preview');if(frame)return{node:frame,item:group(),point:pointInPreview(event)};return null;}
  document.addEventListener('pointermove',event=>{if(!pointerDrop)return;const pending=pointerDrop;if(!pending.active&&Math.hypot(event.clientX-pending.startX,event.clientY-pending.startY)>6){pending.active=true;try{pending.node.setPointerCapture(pending.pointer);}catch(_){}pending.node.classList.add('dragging');document.body.classList.add('pointer-dragging');const ghost=document.createElement('div');ghost.className='drag-ghost';const id=pending.data.asset||state.groups.find(item=>item.id===pending.data.group)?.panels.find(panel=>panel.id===pending.data.panel)?.asset;ghost.textContent=id?filename(assets.get(id)):'Panel';document.body.append(ghost);pending.ghost=ghost;}if(!pending.active)return;event.preventDefault();event.stopPropagation();pending.ghost.style.left=`${event.clientX+12}px`;pending.ghost.style.top=`${event.clientY+12}px`;clearDropHighlights();pending.target=pointerDestination(event);if(pending.target){pending.target.node.classList.add('drop-over');if(pending.target.below!==undefined)pending.target.node.classList.add(pending.target.below?'drop-after':'drop-before');}},{capture:true,passive:false});
  function endPointerDrop(event){if(!pointerDrop)return;const pending=pointerDrop;pointerDrop=null;try{pending.node.releasePointerCapture(pending.pointer);}catch(_){}pending.node.classList.remove('dragging');pending.ghost?.remove();document.body.classList.remove('pointer-dragging');clearDropHighlights();if(!pending.active)return;event.preventDefault();event.stopPropagation();suppressClick=Infinity;const target=pointerDestination(event)||pending.target;if(target?.item)receiveDrop(event,target.item,target.index,target.point,pending.data);suppressClick=performance.now()+1000;}
  document.addEventListener('pointerup',endPointerDrop,true);document.addEventListener('pointercancel',event=>{if(pointerDrop){const pending=pointerDrop;pointerDrop=null;pending.ghost?.remove();pending.node.classList.remove('dragging');document.body.classList.remove('pointer-dragging');clearDropHighlights();}},true);
  function renderGroupControls() {
    $('group-choice').replaceChildren(...state.groups.map(item=>option(item.id,item.name))); $('group-choice').value=group().id;
    $('group-tabs').replaceChildren(...state.groups.map(item=>{const button=document.createElement('button');button.className='group-tab'+(item.id===group().id?' active':'');button.dataset.groupId=item.id;button.textContent=item.name; const count=document.createElement('small');count.textContent=item.panels.length;button.append(count); button.setAttribute('aria-label',`Assembly group: ${item.name}`);button.onclick=()=>switchGroup(item.id);makeDropTarget(button,item);return button;}));
    for(const key of ['name','filename','layout','width','gap','padding','minHeight']){const field=$('group-'+key);field.value=group()[key]??(key==='minHeight'?900:'');field.setCustomValidity('');}
    $('poster-settings').hidden=group().layout!=='poster';$('group-width-label').textContent=group().layout==='poster'?'Minimum width at 1×, px':'Width at 1×, px'; $('poster-snap').checked=group().snap!==false; $('delete-group').disabled=state.groups.length===1; $('export-scale').value=state.scale; $('template-name').value=state.name;
  }
  function switchGroup(id){currentGroup=id;selected=-1;selectedElement='';zoom=1;renderGroupControls();renderOrder();renderColours();renderSelection();renderPreview();dismissOldDownload();}
  function reorder(index,target){group().panels=C.movePanel(group().panels,index,target);selected=target;selectedElement='';changed();}
  function renderOrder() {
    $('panel-count').textContent=`${group().panels.length} panels`;
    $('panel-order').replaceChildren(...group().panels.map((panel,index)=>{
      const row=document.createElement('li');row.className='order-row'+(index===selected?' selected':'');row.draggable=false;row.dataset.panelId=panel.id;wirePointerDrag(row,{group:group().id,panel:panel.id});
      const position=document.createElement('input');position.type='number';position.className='position';position.min=1;position.max=group().panels.length;position.value=index+1;position.setAttribute('aria-label',`Position for ${filename(assets.get(panel.asset))}`);
      position.onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();const target=Number(position.value)-1;if(!Number.isInteger(target)||target<0||target>=group().panels.length){status(`Enter a position from 1 to ${group().panels.length}.`,true);position.value=index+1;return;}reorder(index,target);}};
      const button=document.createElement('button');button.className='panel-select';button.textContent=filename(assets.get(panel.asset));button.setAttribute('aria-pressed',String(index===selected));button.onclick=()=>{if(performance.now()<suppressClick)return;selected=index;selectedElement='';renderOrder();renderSelection();markSelection();}; row.append(position,button);
      for(const [name,label,delta] of [['up','Move up',-1],['down','Move down',1],['remove','Remove panel',0]]){const control=document.createElement('button');control.className='icon-button';control.innerHTML=icon(name);control.setAttribute('aria-label',`${label}: ${filename(assets.get(panel.asset))}`);control.title=label;control.disabled=delta===-1&&index===0||delta===1&&index===group().panels.length-1;control.onclick=()=>{if(delta)reorder(index,index+delta);else{group().panels.splice(index,1);cleanMemberships();selected=Math.min(index,group().panels.length-1);selectedElement='';changed();renderGroupControls();}};row.append(control);}
      row.ondragstart=event=>{if(event.target.closest('input')){event.preventDefault();return;}dragPayload={group:group().id,panel:panel.id};event.dataTransfer.setData(MIME,JSON.stringify(dragPayload));event.dataTransfer.effectAllowed='move';row.classList.add('dragging');};row.ondragend=()=>{dragPayload=null;row.classList.remove('dragging');clearDropHighlights();};makeDropTarget(row,group(),index);return row;
    }));
    if(!group().panels.length){const item=document.createElement('li');item.className='empty';item.textContent='Drop a panel here.';$('panel-order').append(item);}makeDropTarget($('panel-order'),group());
  }

  function hexControl(container,label,value,update){const row=document.createElement('div');row.className='colour-row';const caption=document.createElement('label');caption.textContent=label;const picker=document.createElement('input');picker.type='color';picker.value=/^#[\da-f]{6}$/i.test(value)?value:'#e5edf0';picker.setAttribute('aria-label',label);const hex=document.createElement('input');hex.type='text';hex.maxLength=7;hex.spellcheck=false;hex.value=picker.value;hex.setAttribute('aria-label',label+' hex');picker.oninput=()=>{hex.value=picker.value;update(picker.value);};hex.oninput=()=>{if(/^#[\da-f]{6}$/i.test(hex.value)){picker.value=hex.value;update(hex.value.toLowerCase());}};hex.onchange=()=>{if(!/^#[\da-f]{6}$/i.test(hex.value)){hex.value=picker.value;status('Use a colour such as #e9b34c.',true);}};row.append(caption,picker,hex);container.append(row);return row;}
  function colourControls(container,target,inherited,update){container.replaceChildren();if(!target)return;for(const key of ['text','line']){const label=key==='text'?'Text colour':'Line colour';const row=hexControl(container,label,target[key]||inherited[key]||(key==='text'?'#e5edf0':'#496370'),value=>{target[key]=value;update(false);});const check=document.createElement('input');check.type='checkbox';check.checked=Boolean(target[key]);check.setAttribute('aria-label','Override '+label.toLowerCase());row.querySelector('label').prepend(check);row.querySelectorAll('input:not([type=checkbox])').forEach(input=>input.disabled=!check.checked);check.onchange=()=>{if(check.checked)target[key]=row.querySelector('input[type=color]').value;else delete target[key];update();};}}
  function renderColours(){const matches=(a,b)=>(a.text||null)===(b.text||null)&&(a.line||null)===(b.line||null)&&(a.lineScope||'rules')===(b.lineScope||'rules');$('colour-preset').value=Object.keys(presets).find(key=>matches(state.theme,presets[key]))||'custom';colourControls($('template-colours'),state.theme,{},changed);colourControls($('group-colours'),group().theme,state.theme,changed);$('line-scope').value=state.theme.lineScope||'rules';renderColourGroups();}
  function renderColourGroups(){
    if(!state.colourGroups.some(item=>item.id===activeColour)){activeColour=state.colourGroups[0]?.id||'';editingColour=false;draftMembers=null;}
    $('colour-groups-list').replaceChildren(...state.colourGroups.map(item=>{
      const row=document.createElement('div');row.className='named-colour-row';row.dataset.colourId=item.id;const swatch=document.createElement('span');swatch.className='swatch';swatch.style.backgroundColor=item.colour;const name=document.createElement('span');name.className='name';name.textContent=item.name;name.title=item.name;
      const edit=document.createElement('button');edit.className='edit';edit.textContent='Edit colour group';edit.setAttribute('aria-label',`Edit colour group: ${item.name}`);edit.setAttribute('aria-pressed',String(editingColour&&item.id===activeColour));edit.onclick=()=>beginColourEditing(item.id);
      const remove=document.createElement('button');remove.className='icon-button';remove.innerHTML=icon('remove');remove.setAttribute('aria-label',`Remove colour group: ${item.name}`);remove.onclick=()=>{if(editingColour&&activeColour===item.id)finishColourEditing(false);restoreSourceMembers(item.members);state.colourGroups=state.colourGroups.filter(candidate=>candidate.id!==item.id);if(activeColour===item.id)activeColour='';changed();};row.append(swatch,name,edit,remove);return row;
    }));
    const item=colourGroup();$('colour-group-properties').hidden=!item;$('named-group-colour').replaceChildren();if(item){$('colour-group-name').value=item.name;$('colour-group-name').setCustomValidity('');hexControl($('named-group-colour'),'Group colour',item.colour,value=>{item.colour=value;const row=[...$('colour-groups-list').children].find(node=>node.dataset.colourId===item.id);if(row)row.querySelector('.swatch').style.backgroundColor=value;changed(false);});$('colour-group-members').textContent=`${new Set(item.members.map(member=>JSON.stringify([member.group,member.panel,member.element]))).size} confirmed elements`;}
    updateTool();
  }
  function beginColourEditing(id){
    if(editingColour){if(activeColour===id){finishColourEditing(false);return;}status('Confirm or cancel the current colour selection first.',true);return;}
    activeColour=id;const item=colourGroup();if(!item)return;editingColour=true;draftMembers=new Map();
    const keyMaps=new Map();for(const member of item.members){const owner=state.groups.find(candidate=>candidate.id===member.group),panel=owner?.panels.find(candidate=>candidate.id===member.panel);if(!panel)continue;if(!keyMaps.has(panel.asset)){const root=C.parseSVG(assets.get(panel.asset).svg).root;keyMaps.set(panel.asset,new Map([...root.querySelectorAll('[data-edit-key]')].map(node=>[node.getAttribute('data-edit-key'),node])));}const node=keyMaps.get(panel.asset).get(member.element),spans=node?.localName==='text'?[...node.querySelectorAll('tspan[data-edit-key]')]:[];if(spans.length){for(const span of spans){const expanded={...member,element:span.getAttribute('data-edit-key')};draftMembers.set(memberKey(expanded),expanded);}}else draftMembers.set(memberKey(member),{...member});}
    renderColourGroups();
  }
  function finishColourEditing(confirm){
    if(confirm&&colourGroup()&&draftMembers){const keys=new Set(draftMembers.keys());restoreSourceMembers(colourGroup().members.filter(member=>!keys.has(memberKey(member))));for(const item of state.colourGroups)if(item.id!==activeColour)item.members=item.members.filter(member=>!keys.has(memberKey(member)));colourGroup().members=[...draftMembers.values()];}
    editingColour=false;draftMembers=null;lastHoverNode=null;lastHoverEvent=null;changed();
  }
  function needsConfirmation(){if(!editingColour)return false;status('Confirm or cancel the colour selection first.',true);return true;}
  function removeMembership(member){const key=memberKey(member);for(const item of state.colourGroups)item.members=item.members.filter(candidate=>memberKey(candidate)!==key);}
  function restoreSourceMembers(members){for(const member of members){const owner=state.groups.find(item=>item.id===member.group),panel=owner?.panels.find(item=>item.id===member.panel);if(!panel)continue;panel.elements[member.element]||={};panel.elements[member.element][member.paint]='original';}}
  function renderSelection(){
    const panel=entry();$('selected-panel-name').textContent=panel?filename(assets.get(panel.asset)):'Select a panel.';
    colourControls($('panel-colours'),panel?.theme,{...state.theme,...group().theme},changed);$('poster-placement-fields').hidden=!panel||group().layout!=='poster';
    if(panel&&group().layout==='poster'){const placement=C.layoutGroup(group(),assets).placements[selected];for(const key of ['x','y','width']){$('panel-'+key).value=placement[key];$('panel-'+key).setCustomValidity('');}}
    $('element-choice').replaceChildren(option('','Select an element…'));editorKeys=[];
    if(panel){const parsed=C.parseSVG(assets.get(panel.asset).svg).root;C.applyTheme(parsed,{...state.theme,...group().theme,...panel.theme},panel.elements);C.applyColourGroups(parsed,group().id,panel.id,state.colourGroups);
      editorKeys=[...parsed.querySelectorAll('[data-edit-key]')].map(node=>{const isText=['text','tspan'].includes(node.localName);return{key:node.getAttribute('data-edit-key'),label:isText?node.textContent.trim().replace(/\s+/g,' '):`${node.localName} · ${node.getAttribute('data-edit-key')}`,isText,fill:C.sourcePaint(node,'fill'),stroke:C.sourcePaint(node,'stroke')};});
      editorKeys.sort((a,b)=>Number(b.isText)-Number(a.isText));$('element-choice').append(...editorKeys.map(item=>option(item.key,item.label.slice(0,90))));
    }
    if(!editorKeys.some(item=>item.key===selectedElement))selectedElement='';$('element-choice').value=selectedElement;$('element-choice').disabled=!panel;renderElement();
  }
  function renderElement(){const item=editorKeys.find(candidate=>candidate.key===selectedElement);$('element-description').textContent=item?.label||'';$('element-colours').replaceChildren();$('reset-element').disabled=!item;if(!item)return;for(const paint of item.isText?['fill']:['fill','stroke']){if(!item[paint]||item[paint]==='none')continue;hexControl($('element-colours'),paint==='fill'?'Element fill':'Element stroke',item[paint],value=>{removeMembership({group:group().id,panel:entry().id,element:item.key,paint});entry().elements[item.key]||={};entry().elements[item.key][paint]=value;changed(false);});}}

  function markSelection(){posterHitAreas();$('preview').querySelectorAll('[data-panel-instance]').forEach(node=>node.classList.toggle('selected',Number(node.getAttribute('data-panel-instance'))===selected));}
  function posterHitAreas(){if(group().layout!=='poster')return;for(const owner of $('preview').querySelectorAll('[data-panel-instance]')){if(owner.querySelector('rect[data-panel-hit]'))continue;const view=owner.getAttribute('viewBox').split(/[\s,]+/).map(Number),rect=document.createElementNS(C.NS,'rect');for(const [key,value]of Object.entries({x:view[0],y:view[1],width:view[2],height:view[3],fill:'transparent','pointer-events':'all','data-panel-hit':'true'}))rect.setAttribute(key,value);owner.prepend(rect);}}
  function applyZoom(){const root=$('preview').firstElementChild;if(!root||root.localName!=='svg')return;const style=getComputedStyle($('preview')),available=$('preview').clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight);if(available<=0)return;const logicalWidth=Number(root.getAttribute('width')),ratio=group().layout==='poster'?logicalWidth/group().width:1;root.style.width=`${Math.max(1,available)*zoom*ratio}px`;root.style.height='auto';$('zoom-readout').value=`${Math.round(zoom*100)}%`;}
  function setZoom(value,point=null){const frame=$('preview'),old=zoom;zoom=Math.max(.08,Math.min(8,value));const rect=frame.getBoundingClientRect(),x=(point?.x??rect.width/2)+frame.scrollLeft,y=(point?.y??rect.height/2)+frame.scrollTop;applyZoom();frame.scrollLeft=x*zoom/old-(point?.x??rect.width/2);frame.scrollTop=y*zoom/old-(point?.y??rect.height/2);clearHover();}
  function renderPreview(){paints=null;hoverTargets=[];const frame=$('preview');frame.classList.toggle('poster',group().layout==='poster');if(!group().panels.length&&group().layout!=='poster'){frame.innerHTML='<p class="preview-empty">Drop panels into an assembly group.</p>';$('dimensions').textContent='Empty group';return;}try{let image;if(group().panels.length)image=C.composeGroup(group(),assets,state.theme,'','preview',state.colourGroups);else{const root=document.createElementNS(C.NS,'svg');const height=group().minHeight||900;root.setAttribute('width',group().width);root.setAttribute('height',height);root.setAttribute('viewBox',`0 0 ${group().width} ${height}`);image={root,width:group().width,height};}frame.replaceChildren(image.root);markSelection();applyZoom();$('dimensions').textContent=`${Math.ceil(image.width*state.scale).toLocaleString()} × ${Math.ceil(image.height*state.scale).toLocaleString()} px at ${state.scale}× · transparent`;updateTool();}catch(error){frame.textContent=error.message;$('dimensions').textContent='Check group settings';status(error.message,true);}}
  function changed(refresh=true){dismissOldDownload();persist();renderPreview();if(refresh!==false){renderOrder();renderColours();renderSelection();}}
  function updateTool(){$('preview').classList.toggle('painting',editingColour);$('preview').classList.toggle('arranging',!editingColour&&group().layout==='poster');document.body.classList.toggle('colour-editing',editingColour);$('selection-controls').hidden=!editingColour;$('edit-group-label').textContent=colourGroup()?.name||'';clearHover();updateSelectionSummary();}
  function selectionMode(event={}){if(!editingColour)return'arrange';const removing=event.ctrlKey||event.metaKey;return removing?(event.shiftKey?'remove-same':'remove-one'):(event.shiftKey?'add-same':'add-one');}
  function updateSelectionSummary(){if(!editingColour||!draftMembers)return;$('selection-summary').textContent=`${new Set([...draftMembers.values()].map(member=>JSON.stringify([member.group,member.panel,member.element]))).size} selected · confirm to apply`;}

  const colourCanvas=document.createElement('canvas').getContext('2d');
  function normalColour(value){if(!value||value==='none'||value==='transparent'||/rgba\([^)]*,\s*0\s*\)/.test(value))return null;colourCanvas.fillStyle='#010203';colourCanvas.fillStyle=value;return colourCanvas.fillStyle.toLowerCase();}
  function paintInventory(){if(paints)return paints;paints=[];for(const node of $('preview').querySelectorAll('[data-edit-key]')){if(node.closest('defs,clipPath,mask,marker,symbol')||!['text','tspan','path','line','polyline','polygon','rect','circle','ellipse','use'].includes(node.localName))continue;if(node.localName==='text'&&node.querySelector('tspan[data-edit-key]'))continue;const owner=node.closest('[data-panel-instance]');if(!owner)continue;const panel=group().panels[Number(owner.getAttribute('data-panel-instance'))];if(!panel)continue;const style=getComputedStyle(node);if(style.display==='none'||style.visibility==='hidden'||Number(style.opacity)===0)continue;for(const paint of ['fill','stroke']){if(paint==='fill'&&node.localName==='line')continue;if(paint==='stroke'&&parseFloat(style.strokeWidth)===0)continue;if(Number(paint==='fill'?style.fillOpacity:style.strokeOpacity)===0)continue;const colour=normalColour(style[paint]);if(colour)paints.push({node,colour,group:group().id,panel:panel.id,element:node.getAttribute('data-edit-key'),paint});}}return paints;}
  function selectionTargets(node,event={}){const mode=selectionMode(event);if(mode==='arrange'||!draftMembers||!node)return[];const inventory=paintInventory(),hits=inventory.filter(item=>item.node===node);if(!hits.length)return[];let strokeFirst=['line','polyline'].includes(node.localName)||(node.localName==='path'&&!node.hasAttribute('fill')&&!node.style.fill);if(node.isPointInStroke&&Number.isFinite(event.clientX)){try{const point=new DOMPoint(event.clientX,event.clientY).matrixTransform(node.getScreenCTM().inverse());if(node.isPointInStroke(point)&&!node.isPointInFill(point))strokeFirst=true;}catch(_){}}const hit=hits.find(item=>item.paint===(strokeFirst?'stroke':'fill'))||hits[0];const matches=mode.endsWith('same')?inventory.filter(item=>item.colour===hit.colour):[hit];return matches.filter(item=>mode.startsWith('add')?!draftMembers.has(memberKey(item)):draftMembers.has(memberKey(item)));}
  function overlayLayer(){const root=$('preview').firstElementChild;if(!root||root.localName!=='svg')return null;let layer=[...root.children].find(node=>node.getAttribute('data-ui-layer')==='true');if(!layer){layer=document.createElementNS(C.NS,'g');layer.setAttribute('data-ui-layer','true');layer.setAttribute('pointer-events','none');root.append(layer);}return layer;}
  function clearHover(){hoverTargets=[];lastHoverNode=null;lastHoverEvent=null;showHover([]);}
  function drawHighlights(layer,items,colour,kind){const root=$('preview').firstElementChild,seen=new Set();for(const item of items){if(seen.has(item.node))continue;seen.add(item.node);try{const box=item.node.getBBox(),transform=root.getScreenCTM().inverse().multiply(item.node.getScreenCTM()),corners=[[box.x,box.y],[box.x+box.width,box.y],[box.x,box.y+box.height],[box.x+box.width,box.y+box.height]].map(([x,y])=>new DOMPoint(x,y).matrixTransform(transform)),xs=corners.map(point=>point.x),ys=corners.map(point=>point.y),rect=document.createElementNS(C.NS,'rect');rect.setAttribute('x',Math.min(...xs)-2);rect.setAttribute('y',Math.min(...ys)-2);rect.setAttribute('width',Math.max(4,Math.max(...xs)-Math.min(...xs)+4));rect.setAttribute('height',Math.max(4,Math.max(...ys)-Math.min(...ys)+4));rect.setAttribute('fill',colour);rect.setAttribute('fill-opacity',kind==='selected'?'.12':'.18');rect.setAttribute('stroke',colour);rect.setAttribute('stroke-width','1.5');rect.setAttribute('vector-effect','non-scaling-stroke');rect.setAttribute('data-selection-state',kind);layer.append(rect);}catch(_){}}}
  function showHover(targets){hoverTargets=targets;const layer=overlayLayer();if(!layer)return;layer.replaceChildren();if(editingColour&&draftMembers){drawHighlights(layer,paintInventory().filter(item=>draftMembers.has(memberKey(item))),'#ffe45d','selected');drawHighlights(layer,targets,'#f49a36','hover');}updateSelectionSummary();}
  function selectPaints(targets,event){if(!editingColour||!draftMembers)return;const adding=selectionMode(event).startsWith('add');for(const item of targets){const member={group:item.group,panel:item.panel,element:item.element,paint:item.paint};if(adding)draftMembers.set(memberKey(member),member);else draftMembers.delete(memberKey(member));}showHover([]);updateSelectionSummary();}
  function pointInPreview(event){const root=$('preview').firstElementChild;if(!root||root.localName!=='svg')return null;return new DOMPoint(event.clientX,event.clientY).matrixTransform(root.getScreenCTM().inverse());}
  function guides(lines){const layer=overlayLayer();if(!layer)return;layer.replaceChildren();const image=C.layoutGroup(group(),assets);for(const guide of lines){const line=document.createElementNS(C.NS,'line');line.setAttribute('x1',guide.axis==='x'?guide.value:0);line.setAttribute('x2',guide.axis==='x'?guide.value:image.width);line.setAttribute('y1',guide.axis==='y'?guide.value:0);line.setAttribute('y2',guide.axis==='y'?guide.value:image.height);line.setAttribute('stroke','#e9b34c');line.setAttribute('stroke-dasharray','4 3');line.setAttribute('vector-effect','non-scaling-stroke');layer.append(line);}}

  $('preview').onpointerdown=event=>{if(busy)return;if(event.button===2){pan={x:event.clientX,y:event.clientY,left:$('preview').scrollLeft,top:$('preview').scrollTop,pointer:event.pointerId};$('preview').setPointerCapture(event.pointerId);$('preview').classList.add('panning');event.preventDefault();return;}if(event.button!==0||editingColour||group().layout!=='poster')return;const owner=event.target.closest('[data-panel-instance]');if(!owner)return;selected=Number(owner.getAttribute('data-panel-instance'));const placement=C.layoutGroup(group(),assets).placements[selected],point=pointInPreview(event);if(!placement||!point)return;drag={panel:entry(),node:owner,offsetX:point.x-placement.x,offsetY:point.y-placement.y,startX:event.clientX,startY:event.clientY,moved:false,pointer:event.pointerId};entry().x=placement.x;entry().y=placement.y;entry().width=placement.width;$('preview').setPointerCapture(event.pointerId);event.preventDefault();markSelection();};
  $('preview').onpointermove=event=>{if(pan){$('preview').scrollLeft=pan.left-(event.clientX-pan.x);$('preview').scrollTop=pan.top-(event.clientY-pan.y);return;}if(drag){const point=pointInPreview(event);if(!point)return;drag.moved ||= Math.hypot(event.clientX-drag.startX,event.clientY-drag.startY)>3;const image=C.layoutGroup(group(),assets),placement=image.placements[selected],root=$('preview').firstElementChild,scale=root.getBoundingClientRect().width/image.width,peers=image.placements.filter(item=>item.panel.id!==drag.panel.id);const result=C.snapPosition({x:point.x-drag.offsetX,y:point.y-drag.offsetY,width:placement.width,height:placement.height},peers,{enabled:group().snap!==false,tolerance:9/scale,minX:group().padding,minY:group().padding});drag.panel.x=result.x;drag.panel.y=result.y;drag.node.setAttribute('x',result.x);drag.node.setAttribute('y',result.y);const grown=C.layoutGroup(group(),assets);root.setAttribute('width',grown.width);root.setAttribute('height',grown.height);root.setAttribute('viewBox',`0 0 ${grown.width} ${grown.height}`);applyZoom();guides(result.guides);return;}if(!editingColour)return;cancelAnimationFrame(hoverFrame);lastHoverNode=event.target.closest('[data-edit-key]');lastHoverEvent={clientX:event.clientX,clientY:event.clientY,ctrlKey:event.ctrlKey,metaKey:event.metaKey,shiftKey:event.shiftKey};hoverFrame=requestAnimationFrame(()=>showHover(selectionTargets(lastHoverNode,lastHoverEvent)));};
  function endPreviewGesture(event){if(pan){try{$('preview').releasePointerCapture(pan.pointer);}catch(_){}pan=null;$('preview').classList.remove('panning');return;}if(!drag)return;const moved=drag.moved;try{$('preview').releasePointerCapture(drag.pointer);}catch(_){}drag=null;if(moved)suppressClick=performance.now()+150;changed();}
  $('preview').onpointerup=endPreviewGesture;$('preview').onpointercancel=endPreviewGesture;$('preview').onpointerleave=()=>{if(!drag&&!pan)clearHover();};$('preview').oncontextmenu=event=>event.preventDefault();
  $('preview').onclick=event=>{if(busy||performance.now()<suppressClick)return;const owner=event.target.closest('[data-panel-instance]');if(!owner)return;selected=Number(owner.getAttribute('data-panel-instance'));selectedElement=event.target.closest('[data-edit-key]')?.getAttribute('data-edit-key')||'';if(editingColour){selectPaints(selectionTargets(event.target.closest('[data-edit-key]'),event),event);return;}renderOrder();renderSelection();markSelection();};
  for(const type of ['keydown','keyup'])document.addEventListener(type,event=>{if(event.key==='Escape'&&type==='keydown'&&editingColour){finishColourEditing(false);return;}if(editingColour&&lastHoverNode?.isConnected){lastHoverEvent={...lastHoverEvent,ctrlKey:event.ctrlKey,metaKey:event.metaKey,shiftKey:event.shiftKey};showHover(selectionTargets(lastHoverNode,lastHoverEvent));}});
  $('preview').addEventListener('wheel',event=>{event.preventDefault();if(drag||pan)return;const rect=$('preview').getBoundingClientRect();setZoom(zoom*Math.exp(-event.deltaY*.0015),{x:event.clientX-rect.left,y:event.clientY-rect.top});},{passive:false});
  $('preview').ondragover=event=>{if(!busy){event.preventDefault();event.dataTransfer.dropEffect=dragPayload?.asset?'copy':'move';$('preview').classList.add('drop-over');}};$('preview').ondragleave=()=> $('preview').classList.remove('drop-over');$('preview').ondrop=event=>receiveDrop(event,group(),group().panels.length,pointInPreview(event));
  $('zoom-out').onclick=()=>setZoom(zoom/1.25);$('zoom-in').onclick=()=>setZoom(zoom*1.25);$('zoom-fit').onclick=()=>{zoom=1;applyZoom();$('preview').scrollTop=$('preview').scrollLeft=0;clearHover();};
  new ResizeObserver(()=>applyZoom()).observe($('preview'));

  async function download(blob,name){const url=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Could not prepare the download.'));reader.readAsDataURL(blob);});const link=$('download-link');link.href=url;link.download=name;link.textContent=`Download ${name}`;link.hidden=false;link.click();}
  async function png(image){const size=C.pixelSize(image.width,image.height,state.scale),url=URL.createObjectURL(new Blob([serializer.serializeToString(image.root)],{type:'image/svg+xml;charset=utf-8'}));try{const picture=new Image();picture.src=url;await picture.decode();const canvas=document.createElement('canvas');canvas.width=size.width;canvas.height=size.height;const context=canvas.getContext('2d');if(!context)throw new Error('The browser could not create the PNG canvas.');context.drawImage(picture,0,0,size.width,size.height);const result=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));canvas.width=canvas.height=1;if(!result)throw new Error('Reduce the width or scale and try again.');return result;}finally{URL.revokeObjectURL(url);}}
  async function exportImage(format){if(busy)return;const invalid=document.querySelector('input:invalid');if(invalid){status(invalid.validationMessage,true);invalid.reportValidity();return;}busy=true;const controls=[...document.querySelectorAll('button,input,select')].map(node=>[node,node.disabled]);controls.forEach(([node])=>node.disabled=true);const target=$('export-target').value;try{await document.fonts.ready;if(target==='groups'){const groups=state.groups.filter(item=>item.panels.length);if(!groups.length)throw new Error('Add a panel before exporting.');const files=[],names=new Set();for(const [index,item]of groups.entries()){status(`Exporting ${item.name} (${index+1}/${groups.length})…`,false,true);const image=C.composeGroup(item,assets,state.theme,seed.fontCSS,`export-${index}`,state.colourGroups),blob=format==='png'?await png(image):new Blob([serializer.serializeToString(image.root)],{type:'image/svg+xml'});let name=C.slug(item.filename),candidate=name,suffix=2;while(names.has(candidate))candidate=`${name}-${suffix++}`;names.add(candidate);files.push({name:`${candidate}.${format}`,data:new Uint8Array(await blob.arrayBuffer())});}await download(C.zipFiles(files),`${C.slug(state.name)}-${format}.zip`);status(`Exported ${files.length} ${format.toUpperCase()} groups.`,false,true);}else{status(`Preparing ${format.toUpperCase()}…`,false,true);const image=target==='all'?C.composeAll(state,assets,seed.fontCSS):C.composeGroup(group(),assets,state.theme,seed.fontCSS,'export',state.colourGroups),name=C.slug(target==='all'?state.name:group().filename),blob=format==='png'?await png(image):new Blob([serializer.serializeToString(image.root)],{type:'image/svg+xml'});await download(blob,`${name}.${format}`);status(`Exported ${name}.${format}.`,false,true);}}catch(error){status(error.message||'Export failed.',true);}finally{busy=false;controls.forEach(([node,disabled])=>node.disabled=disabled);}}
  async function importTemplate(input,quiet=false){const additions=[];for(const asset of input.assets||[]){if(assets.has(asset.id)&&!assets.get(asset.id).custom)throw new Error('Use a separate filename for an edited bundled SVG.');additions.push(C.assetFromSVG(asset.id,asset.name||asset.id,asset.svg,asset.category));}const candidateAssets=new Map(assets);additions.forEach(asset=>candidateAssets.set(asset.id,asset));const candidate=C.validateTemplate(input,candidateAssets);additions.forEach(asset=>assets.set(asset.id,asset));state=candidate;currentGroup=state.groups[0].id;selected=-1;selectedElement='';activeColour=state.colourGroups[0]?.id||'';zoom=1;categories();renderLibrary();renderGroupControls();changed();if(!quiet)status(`Loaded ${state.name}.`);}

  $('search').oninput=renderLibrary;$('category').onchange=renderLibrary;$('group-choice').onchange=()=>switchGroup($('group-choice').value);
  for(const key of ['name','filename','width','gap','padding','minHeight']){const field=$('group-'+key);field.oninput=()=>{field.setCustomValidity('');if(['name','filename'].includes(key)){group()[key]=field.value;persist();dismissOldDownload();$('group-choice').selectedOptions[0].textContent=group().name||'Unnamed group';const tab=[...$('group-tabs').children].find(node=>node.dataset.groupId===group().id);if(tab){tab.firstChild.textContent=group().name;tab.setAttribute('aria-label',`Assembly group: ${group().name}`);}return;}const candidate=C.copy(state),item=candidate.groups.find(item=>item.id===group().id);item[key]=Number(field.value);try{C.validateTemplate(candidate,assets);group()[key]=item[key];changed();}catch(error){field.setCustomValidity(error.message);status(error.message,true);}};}
  $('group-layout').onchange=()=>{const candidate=C.copy(state),item=candidate.groups.find(item=>item.id===group().id),layout=$('group-layout').value;if(layout==='poster'&&item.layout!=='poster')startPoster(item);item.layout=layout;try{state=C.validateTemplate(candidate,assets);renderGroupControls();changed();}catch(error){status(error.message,true);$('group-layout').value=group().layout;}};
  $('poster-snap').onchange=()=>{group().snap=$('poster-snap').checked;persist();};
  $('poster-add-column').onclick=()=>{const item=group(),width=C.layoutGroup(item,assets).width+(item.panels[0]?.width||300)+item.gap,candidate=C.copy(state);candidate.groups.find(group=>group.id===item.id).width=width;try{C.validateTemplate(candidate,assets);item.width=width;renderGroupControls();changed();}catch(error){status(error.message,true);}};
  for(const key of ['x','y','width'])$('panel-'+key).oninput=()=>{if(!entry())return;const field=$('panel-'+key);field.setCustomValidity('');const candidate=C.copy(state),item=candidate.groups.find(item=>item.id===group().id),panel=item.panels[selected];panel[key]=Number(field.value);try{C.validateTemplate(candidate,assets);entry()[key]=panel[key];changed(false);}catch(error){field.setCustomValidity(error.message);status(error.message,true);}};
  $('new-group').onclick=()=>{const id=uniqueID('group');state.groups.push({id,name:`Group ${state.groups.length+1}`,filename:`group-${state.groups.length+1}`,layout:'vertical',width:620,gap:20,padding:0,minHeight:900,snap:true,theme:{},panels:[]});switchGroup(id);persist();};
  $('delete-group').onclick=()=>{if(state.groups.length<2)return;const id=group().id;state.groups=state.groups.filter(item=>item.id!==id);cleanMemberships();switchGroup(state.groups[0].id);persist();};
  $('template-name').oninput=()=>{state.name=$('template-name').value;persist();dismissOldDownload();};
  $('export-scale').onchange=()=>{state.scale=Number($('export-scale').value);changed();};$('line-scope').onchange=()=>{state.theme.lineScope=$('line-scope').value;changed();};$('colour-preset').onchange=()=>{if(presets[$('colour-preset').value]){state.theme=C.copy(presets[$('colour-preset').value]);changed();}};
  function createColourGroup(){if(needsConfirmation())return;const name=$('new-colour-name').value.trim();if(!name){status('Name the colour group.',true);$('new-colour-name').focus();return;}if(state.colourGroups.some(item=>item.name.toLowerCase()===name.toLowerCase())){status('Choose a unique colour group name.',true);return;}activeColour=uniqueID('colour');state.colourGroups.push({id:activeColour,name,colour:'#e5edf0',members:[]});$('new-colour-name').value='';persist();beginColourEditing(activeColour);}
  $('create-colour-group').onclick=createColourGroup;$('new-colour-name').onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();createColourGroup();}};
  $('colour-group-name').oninput=()=>{const item=colourGroup(),field=$('colour-group-name'),name=field.value.trim();field.setCustomValidity('');if(!item)return;if(!name||state.colourGroups.some(candidate=>candidate.id!==item.id&&candidate.name.toLowerCase()===name.toLowerCase())){field.setCustomValidity('Choose a unique, non-empty colour group name.');return;}item.name=name;const row=[...$('colour-groups-list').children].find(node=>node.dataset.colourId===item.id);if(row){row.querySelector('.name').textContent=name;row.querySelector('.edit').setAttribute('aria-label',`Edit colour group: ${name}`);}persist();updateTool();};
  $('clear-colour-group').onclick=()=>{if(editingColour&&draftMembers){draftMembers.clear();showHover([]);updateSelectionSummary();}else if(colourGroup()){restoreSourceMembers(colourGroup().members);colourGroup().members=[];changed();}};
  $('confirm-selection').onclick=()=>finishColourEditing(true);$('cancel-selection').onclick=()=>finishColourEditing(false);
  $('element-choice').onchange=()=>{selectedElement=$('element-choice').value;renderElement();};$('reset-element').onclick=()=>{if(entry()&&selectedElement){delete entry().elements[selectedElement];for(const paint of ['fill','stroke'])removeMembership({group:group().id,panel:entry().id,element:selectedElement,paint});changed();}};
  $('preview-background').onchange=()=> $('preview').classList.toggle('light',$('preview-background').value==='light');$('export-png').onclick=()=>{if(!needsConfirmation())exportImage('png');};$('export-svg').onclick=()=>{if(!needsConfirmation())exportImage('svg');};
  $('save-template').onclick=async()=>{if(needsConfirmation())return;try{C.validateTemplate(state,assets);await download(new Blob([JSON.stringify(payload(),null,2)],{type:'application/json'}),`${C.slug(state.name)}.json`);status('Saved template.',false,true);}catch(error){status(error.message,true);}};
  seed.templates.forEach((item,index)=>$('template-choice').append(option(index,item.name)));$('load-preset').onclick=()=>{if(!needsConfirmation())importTemplate(C.copy(seed.templates[Number($('template-choice').value)])).catch(error=>status(error.message,true));};
  $('import-template').onclick=()=>{if(!needsConfirmation())$('template-file').click();};$('template-file').onchange=async()=>{try{const file=$('template-file').files[0];if(file)await importTemplate(JSON.parse(await file.text()));}catch(error){status(`Could not load template: ${error.message}`,true);}finally{$('template-file').value='';}};
  $('import-svg').onclick=()=> $('svg-files').click();$('svg-files').onchange=async()=>{try{const pending=[];for(const file of $('svg-files').files){let id=`imported/${file.name}`,suffix=2;while(assets.has(id)||pending.some(asset=>asset.id===id))id=`imported/${suffix++}-${file.name}`;pending.push(C.assetFromSVG(id,file.name.replace(/\.svg$/i,''),await file.text()));}pending.forEach(asset=>assets.set(asset.id,asset));categories();renderLibrary();persist();status(`Imported ${pending.length} SVG files.`);}catch(error){status(`Could not import SVGs: ${error.message}`,true);}finally{$('svg-files').value='';}};
  categories();renderLibrary();renderGroupControls();renderOrder();renderColours();renderSelection();renderPreview();
  try{const saved=localStorage.getItem('autoarm-panel-assembler-v1');if(saved)importTemplate(JSON.parse(saved),true).catch(error=>status(`Could not restore the session: ${error.message}`,true));}catch(_){/* File templates remain available when storage is disabled. */}
})();
